In [6]:
import pandas as pd
from bs4 import BeautifulSoup

In [10]:
df = pd.read_csv("../database.csv")

In [11]:
df

,rg,sequence,text
0,RG-50.030.0001,0,Q: I need you to start off by telling me your ...
1,RG-50.030.0001,1,A: My name David Kochalski. I was born in a sm...
2,RG-50.030.0001,2,Q: Tell me a little bit about your family life...
3,RG-50.030.0001,3,"A: Well, we were very hard working, six childr..."
4,RG-50.030.0001,4,"Q: Did you go to a public school, a private sc..."
...,...,...,...
395318,RG-50.549.05.0014,293,A: I really couldn’t tell you. Something inner...
395319,RG-50.549.05.0014,294,Q: Were you in a combat unit while you were in...
395320,RG-50.549.05.0014,295,A: I was actually in the Signal outfit. The fi...
395321,RG-50.549.05.0014,296,Q: What was your rank when you retired from th...
395322,RG-50.549.05.0014,297,"A: I was E-8, Master Sergeant. I graduated fro..."

In [12]:
import pandas as pd
from bs4 import BeautifulSoup

# assuming your dataframe is named df

# Group the dataframe by 'rg' and sort by 'sequence' within each group
df = df.sort_values(by=['rg', 'sequence'])

# Initialize BeautifulSoup
soup = BeautifulSoup(features="html.parser")

# Iterate over the groups
for rg, group in df.groupby('rg'):
    # Initialize a new HTML document
    html = soup.new_tag('html')
    
    # Add a head section with some CSS
    head = soup.new_tag('head')
    style = soup.new_tag('style')
    style.string = """
    body {
        font-family: Arial, sans-serif;
        margin: 0 auto;
        width: 80%;
        padding: 20px;
    }
    h1 {
        color: #333;
    }
    p {
        line-height: 1.6;
    }
    """
    head.append(style)
    html.append(head)
    
    # Add a body section
    body = soup.new_tag('body')
    
    # Add a header with the rg number
    h1 = soup.new_tag('h1')
    h1.string = rg
    body.append(h1)
    
    # For each row in the group, create a new 'p' tag with the 'id' attribute set to the sequence number and the text set to the text field
    for _, row in group.iterrows():
        p = soup.new_tag('p', id=row['sequence'])
        p.string = row['text']
        body.append(p)
    
    # Append body to html
    html.append(body)
    
    # Construct the filename
    filename = f'../testimonies/{rg.replace(".", "_")}.html'
    
    # Write the HTML to a file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html.prettify())